---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH
    - /bin/npm install --production=false
    - /bin/npm run build
    - /bin/mkdir -p uploads
    - /bin/chmod 755 uploads

